import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";
import { StyleSheet } from "react-native";
import omit from "lodash/omit";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ style = {}, color, ...rest }) => {
    const flattenedStyle = StyleSheet.flatten(style);
    const Path = props => (
        <Path_ fill={color || flattenedStyle.color} {...props} />
    );
    const props = { style: omit(flattenedStyle, ["color"]), ...rest };
    return (
        <Svg viewBox="0 0 244 89" {...props}>
            <Path d="M153.7 57.6h-10.1v-7.1h9.6v-2.3h-9.6v-6.6h10.1v-2.3H141v20.5h12.7v-2.2zm12 2.3l7.5-20.5h-2.7l-6.1 17.4h-.1l-6.1-17.4h-2.7l7.5 20.5h2.7zm22.8-2.3h-10.1v-7.1h9.6v-2.3h-9.6v-6.6h10.1v-2.3h-12.7v20.5h12.7v-2.2zm6.1 2.3V43.8h.1l11.2 16.1h2.5V39.3h-2.5v16.1h-.1l-11.2-16.1h-2.5v20.5h2.5zm25.8 0V41.7h6.5v-2.3h-15.5v2.3h6.5v18.2h2.5zm8.3-5.7c.2 3.6 3.2 6 7.6 6 4.7 0 7.7-2.3 7.7-6.1 0-2.9-1.7-4.6-6-5.6l-2.1-.6c-2.8-.7-3.9-1.6-3.9-3.2 0-2 1.8-3.4 4.5-3.4s4.4 1.4 4.7 3.6h2.6c-.1-3.4-3.1-5.9-7.1-5.9-4.3 0-7.2 2.4-7.2 5.8 0 2.8 1.7 4.5 5.4 5.4l2.6.7c2.8.7 4 1.8 4 3.5 0 2-2 3.5-4.8 3.5-2.9 0-5-1.5-5.3-3.7h-2.7zM119.4 0h1.7c-6.5 27.3-13.5 54.5-20.2 81.7-.6 2.4-1.2 4.9-2 7.3h-1.7c7.4-29.6 14.7-59.4 22.2-89zM0 28.4h15.3l-.1 6.6H12v28.9h11.4v-7.1H31v13.9l-31 .1v-6.9h3.3V35H0v-6.6zm41.9 0h15V35h-3s5 18.2 7.8 26.8c3.1-8.4 8-26.8 8-26.8h-3v-6.6h14.9V35h-3.2s-7.5 24-11.7 35.7c-3.2-.1-10 0-10 0s-2.5-6.9-3.5-10.2C50.5 52.2 45 34.9 45 34.9h-3.2c.1 0 0-4.5.1-6.5z" />
        </Svg>
    );
};
