import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";
import { StyleSheet } from "react-native";
import omit from "lodash/omit";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ style = {}, color, ...rest }) => {
    const flattenedStyle = StyleSheet.flatten(style);
    const Path = props => (
        <Path_ fill={color || flattenedStyle.color} {...props} />
    );
    const props = { style: omit(flattenedStyle, ["color"]), ...rest };
    return (
        <Svg viewBox="0 0 32 30" {...props}>
            <Path d="M16 29.75A15.69 15.69 0 0 1 7 1.2a5.31 5.31 0 0 1 3.74-.88A2.63 2.63 0 0 1 12.5 1.4c.93 1.11.49 2.5.14 3.62-.27.87-.43 1.46-.18 1.77.9 1.08 2.32.7 4.73-.06 2.75-.86 6.16-1.93 10-.15 5.69 2.92 4.29 10.27 3.95 11.72A15.78 15.78 0 0 1 16 29.75zm-6-28a3.94 3.94 0 0 0-2.16.68A14.19 14.19 0 0 0 16 28.25a14.25 14.25 0 0 0 13.63-10.33c.29-1.22 1.53-7.59-3.15-10-3.24-1.52-6.21-.58-8.84.24-2.44.77-4.74 1.5-6.34-.43-.78-1-.41-2.13-.09-3.16s.51-1.76.09-2.27a1.22 1.22 0 0 0-.84-.51 2.45 2.45 0 0 0-.46-.04z" />
            <Path d="M22.75 17.52a3.47 3.47 0 1 1 3.46-3.47 3.47 3.47 0 0 1-3.46 3.47zm0-5.44a2 2 0 1 0 2 2 2 2 0 0 0-2-2zM6.44 16.16a2.11 2.11 0 1 1 2.11-2.11 2.11 2.11 0 0 1-2.11 2.11zm0-2.72a.61.61 0 0 0 0 1.22.61.61 0 1 0 0-1.22zM9.83 23a2.11 2.11 0 1 1 2.11-2.11A2.12 2.12 0 0 1 9.83 23zm0-2.72a.61.61 0 0 0-.61.61.62.62 0 0 0 .61.61.61.61 0 0 0 .61-.61.61.61 0 0 0-.61-.65zM17.31 25.67a2.11 2.11 0 1 1 2.11-2.11 2.11 2.11 0 0 1-2.11 2.11zm0-2.71a.61.61 0 1 0 0 1.21.61.61 0 1 0 0-1.21z" />
        </Svg>
    );
};
