import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";
import { StyleSheet } from "react-native";
import omit from "lodash/omit";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ style = {}, color, ...rest }) => {
    const flattenedStyle = StyleSheet.flatten(style);
    const Path = props => (
        <Path_ fill={color || flattenedStyle.color} {...props} />
    );
    const props = { style: omit(flattenedStyle, ["color"]), ...rest };
    return (
        <Svg viewBox="0 0 30 30" {...props}>
            <Path d="M8.47 26H2.64l-.49-6.81-1.9-.95v-4.17a3.55 3.55 0 0 1 3.55-3.55h3.73a3.55 3.55 0 0 1 3.21 2l-1.35.64A2.07 2.07 0 0 0 7.53 12H3.8a2.05 2.05 0 0 0-2 2.05v3.27l1.83.91.37 6.29h4.47zM5.67 9.22a3.55 3.55 0 1 1 3.55-3.55 3.56 3.56 0 0 1-3.55 3.55zm0-5.6a2.05 2.05 0 1 0 2.05 2.05 2.05 2.05 0 0 0-2.05-2.05zM27.37 26h-5.84v-1.5H26l.45-6.27 1.83-.91v-3.25A2.05 2.05 0 0 0 26.2 12h-3.73a2.07 2.07 0 0 0-1.86 1.17l-1.35-.64a3.55 3.55 0 0 1 3.21-2h3.73a3.55 3.55 0 0 1 3.55 3.55v4.19l-1.9.95zM24.33 9.22a3.55 3.55 0 1 1 3.55-3.55 3.56 3.56 0 0 1-3.55 3.55zm0-5.6a2.05 2.05 0 1 0 2.05 2.05 2.05 2.05 0 0 0-2.05-2.05z" />
            <Path d="M18.5 29.75h-7l-.5-7.59-2.37-.48V15a4.49 4.49 0 0 1 4.48-4.48h3.74a4.49 4.49 0 0 1 4.5 4.48v6.68l-2.35.48zm-5.6-1.5h4.2l.45-7.34 2.3-.46V15a3 3 0 0 0-3-3h-3.72a3 3 0 0 0-3 3v5.45l2.3.46zM15 9.22a4.49 4.49 0 1 1 4.48-4.49A4.49 4.49 0 0 1 15 9.22zm0-7.47a3 3 0 1 0 3 3 3 3 0 0 0-3-3z" />
        </Svg>
    );
};
