import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";
import { StyleSheet } from "react-native";
import omit from "lodash/omit";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ style = {}, color, ...rest }) => {
    const flattenedStyle = StyleSheet.flatten(style);
    const Path = props => (
        <Path_ fill={color || flattenedStyle.color} {...props} />
    );
    const props = { style: omit(flattenedStyle, ["color"]), ...rest };
    return (
        <Svg viewBox="0 0 29 30" {...props}>
            <Path d="M2.46 28.31a2.18 2.18 0 0 1-1.55-.66 2.17 2.17 0 0 1-.14-3L18.69 2.29a5.32 5.32 0 0 1 3.83-2 5.49 5.49 0 0 1 4.2 1.56 5.4 5.4 0 0 1-.45 8L3.89 27.79a2.25 2.25 0 0 1-1.43.52zM22.88 1.75h-.26a3.8 3.8 0 0 0-2.76 1.46L1.94 25.61a.72.72 0 0 0 1 1L25.33 8.7a3.8 3.8 0 0 0 1.47-2.82 3.86 3.86 0 0 0-1.13-3 4 4 0 0 0-2.79-1.13zM1.36 25.14z" />
            <Path d="M11.218 21.07l1.065-1.057 8.395 8.462-1.065 1.057zM23.14 19.15a4.88 4.88 0 0 1-3.46-1.41L9.35 7.48a3.44 3.44 0 0 0-4.8 0 3.43 3.43 0 0 0 0 4.8l4 4-1.06 1.06-4-4a4.93 4.93 0 0 1 0-6.92 5 5 0 0 1 6.92 0l10.33 10.26a3.39 3.39 0 1 0 4.8-4.8l-4.4-4.4 1.06-1.06 4.4 4.4a5 5 0 0 1 0 6.92 4.88 4.88 0 0 1-3.46 1.41zM15.815 2.154l1.06-1.06 2.129 2.128-1.06 1.06z" />
            <Path d="M19.95 7.529l2.615-2.503 1.037 1.084-2.616 2.503z" />
        </Svg>
    );
};
