import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";
import { StyleSheet } from "react-native";
import omit from "lodash/omit";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ style = {}, color, ...rest }) => {
    const flattenedStyle = StyleSheet.flatten(style);
    const Path = props => (
        <Path_ fill={color || flattenedStyle.color} {...props} />
    );
    const props = { style: omit(flattenedStyle, ["color"]), ...rest };
    return (
        <Svg viewBox="0 0 29 30" {...props}>
            <Path d="M22.5.25a6.35 6.35 0 0 0-6.3 5.6H.38L11.55 19v9.27H5v1.5h14.6v-1.5h-6.5V19l6-7.07A6.35 6.35 0 1 0 22.5.25zm-1.61 7.1l-3.46 4.1H7.11l-3.49-4.1zM16.17 13l-3.87 4.54L8.39 13zm6.33-1.5a4.86 4.86 0 0 1-2.5-.74l4.13-4.91h-6.4a4.84 4.84 0 1 1 4.77 5.6z" />
        </Svg>
    );
};
