import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";
import { StyleSheet } from "react-native";
import omit from "lodash/omit";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ style = {}, color, ...rest }) => {
    const flattenedStyle = StyleSheet.flatten(style);
    const Path = props => (
        <Path_ fill={color || flattenedStyle.color} {...props} />
    );
    const props = { style: omit(flattenedStyle, ["color"]), ...rest };
    return (
        <Svg viewBox="0 0 32 30" {...props}>
            <Path d="M10.87 16.25a2.25 2.25 0 1 0 2.23 2.25 2.24 2.24 0 0 0-2.23-2.25zm0 3a.75.75 0 1 1 .73-.75.74.74 0 0 1-.73.75zM20.73 16.25A2.25 2.25 0 1 0 23 18.5a2.24 2.24 0 0 0-2.27-2.25zm0 3a.75.75 0 1 1 .73-.75.74.74 0 0 1-.73.75z" />
            <Path d="M27.51 12.35a12.63 12.63 0 0 0-9.82-7.95 6.1 6.1 0 0 1 5-2.65V.25a7.62 7.62 0 0 0-6.7 4h-.19a12.61 12.61 0 0 0-11.71 8.1 4.74 4.74 0 0 0 0 9.3 12.51 12.51 0 0 0 23.42 0 4.74 4.74 0 0 0 0-9.3zm-.61 7.87h-.49l-.16.46a11 11 0 0 1-20.9 0l-.16-.46H4.7a3.23 3.23 0 0 1 0-6.44h.49l.16-.46a11.1 11.1 0 0 1 10-7.51 7.76 7.76 0 0 0-.3 2.19h1.5a6.29 6.29 0 0 1 .39-2.18 11.11 11.11 0 0 1 9.31 7.46l.16.46h.49a3.23 3.23 0 0 1 0 6.44z" />
        </Svg>
    );
};
