import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";
import { StyleSheet } from "react-native";
import omit from "lodash/omit";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ style = {}, color, ...rest }) => {
    const flattenedStyle = StyleSheet.flatten(style);
    const Path = props => (
        <Path_ fill={color || flattenedStyle.color} {...props} />
    );
    const props = { style: omit(flattenedStyle, ["color"]), ...rest };
    return (
        <Svg viewBox="0 0 30 30" {...props}>
            <Path d="M2.614 3.543l.922-.917 6.487 6.524-.921.916zM21.76 18.92l-.92.91 7.08 7.13-1.1 1.12-7.09-7.13-.92.92 8.01 8.05 2.94-2.96-8-8.04z" />
            <Path d="M15.17 23.3l12.61-12.68a6.42 6.42 0 0 0 0-9.06l-.46-.46-11.64 11.71-2.12-2.14a2.19 2.19 0 0 0 0-3.06L6.06.08 5.14 1l7.49 7.52a.91.91 0 0 1 0 1.25L9.71 12.7a.88.88 0 0 1-1.22 0L1 5.17l-.92.92 7.48 7.53a2.19 2.19 0 0 0 3.06 0l2.12 2.13-2.12 2.13-.42.42L1.6 27l2.94 3L12 22.38l-.92-.92-6.54 6.62L3.44 27l7.68-7.73zm-3.64-10.59l1.11-1.12 2.12 2.14-1.1 1.11zM27.29 3a5.13 5.13 0 0 1-.43 6.74L15.17 21.46 12 18.31z" />
        </Svg>
    );
};
