import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";
import { StyleSheet } from "react-native";
import omit from "lodash/omit";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ style = {}, color, ...rest }) => {
    const flattenedStyle = StyleSheet.flatten(style);
    const Path = props => (
        <Path_ fill={color || flattenedStyle.color} {...props} />
    );
    const props = { style: omit(flattenedStyle, ["color"]), ...rest };
    return (
        <Svg viewBox="0 0 33 29" {...props}>
            <Path d="M24.1.25c-3.47 0-6.38 1.16-7.7 2.88C15.08 1.41 12.17.25 8.7.25 4 .25.25 2.42.25 5.2V29h1.5c0-1.67 2.79-3.45 7-3.45s7 1.78 7 3.45h1.5c0-1.67 2.79-3.45 7-3.45s7 1.78 7 3.45h1.5V5.2C32.55 2.42 28.84.25 24.1.25zM8.7 24.05a11 11 0 0 0-6.95 2.1V5.2c0-1.67 2.79-3.45 7-3.45s7 1.78 7 3.45v21a10.9 10.9 0 0 0-7.05-2.15zm22.35 2.1a11 11 0 0 0-6.95-2.1 10.9 10.9 0 0 0-7 2.12V5.2c0-1.67 2.79-3.45 7-3.45s7 1.78 7 3.45z" />
        </Svg>
    );
};
