import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";
import { StyleSheet } from "react-native";
import omit from "lodash/omit";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ style = {}, color, ...rest }) => {
    const flattenedStyle = StyleSheet.flatten(style);
    const Path = props => (
        <Path_ fill={color || flattenedStyle.color} {...props} />
    );
    const props = { style: omit(flattenedStyle, ["color"]), ...rest };
    return (
        <Svg viewBox="0 0 30 30" {...props}>
            <Path d="M15 .25A14.75 14.75 0 1 0 29.75 15 14.77 14.77 0 0 0 15 .25zm.47 14.06a14.86 14.86 0 0 1-1.84-5.51c4.59-.87 8.9.19 14.56 7.33a13.17 13.17 0 0 1-1.75 5.53 14.39 14.39 0 0 0-2.1-3.07 14.42 14.42 0 0 0-8.87-4.28zm-6.33 3.27C6 13.44 6.12 7.45 7.28 4.25a13.11 13.11 0 0 1 6.18-2.4 14.33 14.33 0 0 0-1.19 3.52A14.37 14.37 0 0 0 14 14.83a14.38 14.38 0 0 1-4.86 2.75zm19.05-3.8c-5.8-6.68-10.46-7.26-14.62-6.5a9.1 9.1 0 0 1 .17-1.62 13.1 13.1 0 0 1 1.47-3.9 13.27 13.27 0 0 1 12.98 12.02zM5.28 6a16.6 16.6 0 0 0 2.27 12 8.72 8.72 0 0 1-1.46.12A13.26 13.26 0 0 1 2 17.39 12.58 12.58 0 0 1 1.75 15a13.24 13.24 0 0 1 3.53-9zM2.4 19.08a14.5 14.5 0 0 0 3.69.49 14.51 14.51 0 0 0 9.15-3.78 14.61 14.61 0 0 1 5.55 1.84c-2.33 4.38-5.86 7-15.13 6.76a13.35 13.35 0 0 1-3.26-5.31zM15 28.25a13.11 13.11 0 0 1-7.52-2.36c8.55-.14 12.18-3 14.56-7.4a11.08 11.08 0 0 1 1.19 1.1 13.23 13.23 0 0 1 2.23 3.52A13.24 13.24 0 0 1 15 28.25z" />
        </Svg>
    );
};
