import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ fill, ...props }) => {
    const Path = props => <Path_ fill={fill} {...props} />;
    return (
        <Svg viewBox="0 0 22 22" {...props}>
            <Path d="M8.62 11l7.94-7.94A1.5 1.5 0 1 0 14.44.94l-9 9a1.49 1.49 0 0 0 0 2.12l9 9a1.5 1.5 0 1 0 2.12-2.12z" />
        </Svg>
    );
};
