import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";
import { StyleSheet } from "react-native";
import omit from "lodash/omit";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ style = {}, color, ...rest }) => {
    const flattenedStyle = StyleSheet.flatten(style);
    const Path = props => (
        <Path_ fill={color || flattenedStyle.color} {...props} />
    );
    const props = { style: omit(flattenedStyle, ["color"]), ...rest };
    return (
        <Svg viewBox="0 0 38 38" {...props}>
            <Path d="M37.75 36.75H.25V3.2h9.06V0h1.5v3.2h16.56V0h1.5v3.2h8.88zm-36-1.5h34.5v-23H1.75zm0-24.5h34.5v-6h-7.38V7h-1.5V4.7H10.81V7h-1.5V4.7H1.75zm30.83 20h-7.42V25h7.42zm-5.92-1.5h4.42v-2.8h-4.42zm-3.95 1.5h-7.42V25h7.42zm-5.92-1.5h4.42v-2.8h-4.42zm-3.95 1.5H5.42V25h7.42zm-5.92-1.5h4.42v-2.8H6.92zm25.66-6.75h-7.42v-5.77h7.42zM26.66 21h4.42v-2.77h-4.42zm-3.95 1.5h-7.42v-5.77h7.42zM16.79 21h4.42v-2.77h-4.42zm-3.95 1.5H5.42v-5.77h7.42zM6.92 21h4.42v-2.77H6.92z" />
        </Svg>
    );
};
