import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ fill, ...props }) => {
    const Path = props => <Path_ fill={fill} {...props} />;
    return (
        <Svg viewBox="0 0 24 24" {...props}>
            <Path d="M3.586 19L19.001 3.585 20.415 5 5 20.415z" />
            <Path d="M3.586 5L5 3.585 20.415 19l-1.414 1.415z" />
        </Svg>
    );
};
