import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";
import { StyleSheet } from "react-native";
import omit from "lodash/omit";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ style = {}, color, ...rest }) => {
    const flattenedStyle = StyleSheet.flatten(style);
    const Path = props => (
        <Path_ fill={color || flattenedStyle.color} {...props} />
    );
    const props = { style: omit(flattenedStyle, ["color"]), ...rest };
    return (
        <Svg viewBox="0 0 16 16" {...props}>
            <Path d="M3.18.8a3 3 0 0 0-1.41.84A2.59 2.59 0 0 0 .8 3.2c0 5.38 6.61 12 12 12a2.54 2.54 0 0 0 1.55-1 3 3 0 0 0 .85-1.43 5 5 0 0 0-1.6-1.62 6 6 0 0 0-2-1.18s-.1 0-.28.27a6.78 6.78 0 0 0-.49.74c-.45.73-.87 1.42-1.49 1.42a.72.72 0 0 1-.34-.03A11.32 11.32 0 0 1 3.62 7 1 1 0 0 1 4 5.85a7 7 0 0 1 1-.68 7.92 7.92 0 0 0 .74-.49C6 4.5 6 4.41 6 4.39a6.21 6.21 0 0 0-1.18-2C3.93 1.24 3.34.82 3.18.8zM12.79 16a10 10 0 0 1-4.48-1.19 16.59 16.59 0 0 1-4.1-3 16.61 16.61 0 0 1-3-4.1A10 10 0 0 1 0 3.2a3.42 3.42 0 0 1 1.22-2.14A3.63 3.63 0 0 1 3.19 0 1.85 1.85 0 0 1 4.3.62a10 10 0 0 1 1.1 1.23A6.8 6.8 0 0 1 6.79 4.4c0 .6-.68 1-1.39 1.45-.28.17-.56.35-.77.51s-.26.27-.27.3a10.6 10.6 0 0 0 5 5 .9.9 0 0 0 .29-.27 7.34 7.34 0 0 0 .52-.77c.44-.71.85-1.39 1.45-1.39a6.8 6.8 0 0 1 2.54 1.38 11.1 11.1 0 0 1 1.24 1.11 1.85 1.85 0 0 1 .6 1.08 3.63 3.63 0 0 1-1.06 2 3.42 3.42 0 0 1-2.15 1.2z" />
        </Svg>
    );
};
