import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ fill, ...props }) => {
    const Path = props => <Path_ fill={fill} {...props} />;
    return (
        <Svg viewBox="0 0 38 38" {...props}>
            <Path d="M19.05 20a6.26 6.26 0 1 1 6.26-6.26A6.27 6.27 0 0 1 19.05 20zm0-11a4.76 4.76 0 1 0 4.76 4.76A4.76 4.76 0 0 0 19.05 9z" />
            <Path d="M19.09 38a.9.9 0 0 1-.61-.24l-.21-.22C8.84 27.3 4.42 18.85 5.14 12.43 6 4.53 13 .27 19.05.27v1.5c-5.43 0-11.63 3.79-12.42 10.82C6 18.5 10.15 26.43 19.06 36.18 28 26.43 32.15 18.5 31.49 12.59c-.79-7-7-10.82-12.41-10.82V.27c6.08 0 13 4.26 13.9 12.16.72 6.42-3.69 14.87-13.13 25.11l-.2.22a.8.8 0 0 1-.56.24z" />
        </Svg>
    );
};
