import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ fill, ...props }) => {
    const Path = props => <Path_ fill={fill} {...props} />;
    return (
        <Svg viewBox="0 0 24 24" {...props}>
            <Path d="M6.5 11.5L15 3l1 1-8 8 8 8-1 1-8.5-8.5-.6-.5z" />
        </Svg>
    );
};
