import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";
import { StyleSheet } from "react-native";
import omit from "lodash/omit";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ style = {}, color, ...rest }) => {
    const flattenedStyle = StyleSheet.flatten(style);
    const Path = props => (
        <Path_ fill={color || flattenedStyle.color} {...props} />
    );
    const props = { style: omit(flattenedStyle, ["color"]), ...rest };
    return (
        <Svg viewBox="0 0 24 24" {...props}>
            <Path d="M18.34 13.25a7.34 7.34 0 1 1-7.17-7v4L19 4.91 11.17.73v3.52a9.34 9.34 0 0 0-8.55 13.48 9.35 9.35 0 0 0 17.72-4.57z" />
        </Svg>
    );
};
