import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";
import { StyleSheet } from "react-native";
import omit from "lodash/omit";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ style = {}, color, ...rest }) => {
    const flattenedStyle = StyleSheet.flatten(style);
    const Path = props => (
        <Path_ fill={color || flattenedStyle.color} {...props} />
    );
    const props = { style: omit(flattenedStyle, ["color"]), ...rest };
    return (
        <Svg viewBox="0 0 24 24" {...props}>
            <Path d="M13.22 13.22L18 6l-7.22 4.78-3.65 5.48L6 18l1.74-1.13zm-4.35 1.91l2.52-3.74 1.22 1.22z" />
            <Path d="M12 22.5A10.39 10.39 0 0 1 1.5 12 10.39 10.39 0 0 1 12 1.5 10.39 10.39 0 0 1 22.5 12 10.39 10.39 0 0 1 12 22.5zm0-20A9.4 9.4 0 0 0 2.5 12a9.4 9.4 0 0 0 9.5 9.5 9.4 9.4 0 0 0 9.5-9.5A9.4 9.4 0 0 0 12 2.5z" />
        </Svg>
    );
};
