import React from "react";
import Svg, { Path as Path_ } from "react-native-svg";

// ATTN: generated by `yarn build-icons`, do not edit
export default ({ fill, ...props }) => {
    const Path = props => <Path_ fill={fill} {...props} />;
    return (
        <Svg viewBox="0 0 24 24" {...props}>
            <Path d="M3.8 6.8h-.4V24h17.3V6.8h-6.4v.9h5.4v15.4H4.3V7.7h5.4v-.9z" />
            <Path d="M8.8 4.5l-.6-.7L12 0l3.8 3.8-.7.7-2.7-2.7v13.6h-.9V1.8z" />
        </Svg>
    );
};
